### ISSUE TITLE
Is there a compiled PDF of this paper? I'd love to read it!

### ISSUE THREAD

**Issue by jonmatthis** [pyqtgraph/IEEEVIS2021-pyqtgraph#1]

**Comment by j9ac9k** [comment]
My apologies for the late reply @jonmatthis this completely slipped my mind!

Here is the PDF of it; we're still waiting to hear back to see if it was accepted.

[IEEEVIS2021__pyqtgraph.pdf](https://github.com/pyqtgraph/IEEEVIS2021-pyqtgraph/files/6605697/IEEEVIS2021__pyqtgraph.pdf)

**Comment by jonmatthis** [comment]
Thank you! This is a really wonderful project and exactly what I have been looking for for quite some time!

Question - In the abstract it mentions the support for "...time-series 3D data represented as 4D arrays..." but I haven't been able to find documentation to describe the implementation of this feature. 

I work with motion capture data, which effectively results in an array of 3d time-series trajectories representing a human (or other animal)'s movement over time so "time-series 3D data represented as 4D arrays" is almost exactly my use case! Could you please point me towards any documentation on how to efficiently utilize this feature of PyQtGraph? 

(also, let me know if you'd prefer to move this question over the to the main GitHub repo)

**Comment by j9ac9k** [comment]
Our documentation needs help, no doubt about that.

In the examples, the 3rd item, Image View, I believe has colored image data with a 4th dimension of time, the red vertical line represents the time point, and it is adjustable by the mouse.

![image](https://user-images.githubusercontent.com/646398/121557156-5cf37280-c9c9-11eb-856a-b24000a6252c.png)

The code is viewable in the example app window we bundle; but here is the source code for the example: https://github.com/pyqtgraph/pyqtgraph/blob/master/examples/ImageView.py

We should definitely migrate this discussion to the Discussion tabs (recently enabled) in the main repo.  I don't work with image data often, so I'm probably not the best person to speak to the capabilities

**Comment by outofculture** [comment]
Hey @jonmatthis,

3D data over time might be better represented with the GL family of widgets
in a 3D plot. Notably, these widgets are less well maintained, but they can
probably get the job done. Maybe have a look at
https://github.com/pyqtgraph/pyqtgraph/blob/master/examples/GLSurfacePlot.py
or GLLinePlotItem.py for relevant examples.

Good luck!

**Comment by j9ac9k** [comment]
🤦🏻 I read 3D as 2D data with color values, not 3D values in space; so yes, what @outofculture said 😆

**Comment by jonmatthis** [comment]
@j9ac9k - I work with video as well, so your comment was also helpful :D

Thanks all for being so responsive and for your work on this wonderful project!
